"""empty message

Revision ID: 58114c4cec03
Revises: 76c5ff91afd2
Create Date: 2024-04-18 15:20:48.257445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58114c4cec03'
down_revision = '76c5ff91afd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###
