"""empty message

Revision ID: f2560b55b7d9
Revises: 68baf3d3115a
Create Date: 2024-04-18 20:58:31.620232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2560b55b7d9'
down_revision = '68baf3d3115a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('genres')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('genres')

    op.create_table('Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='Genre_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='Genre_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Genre_pkey')
    )
    # ### end Alembic commands ###
